replicaCount: 1
image:
  repository: mykytakhomenko/kbot
  tag: "v1.0.6-81edd88"
  arch: amd64
  os: linux
  registry: "docker.io"
secret:
  envName: "TELE_TOKEN"
  tokenKey: "token"
  tokenName: "kbot"
securityContext:
  privileged: true
