replicaCount: 1
image:
  repository: mykytakhomenko/kbot
  tag: "v1.0.6-a5ca94d"
  arch: amd64
  os: linux
  registry: ""
secret:
  envName: "TELE_TOKEN"
  tokenKey: "token"
  tokenName: "kbot"
securityContext:
  privileged: true
