name: Encrypt and Commit Secret

on:
  workflow_dispatch:   # manual trigger only

jobs:
  encrypt-secret:
    runs-on: ubuntu-latest

    permissions:
      contents: write   # only what is needed

    steps:
      - name: Checkout Flux repo
        uses: actions/checkout@v4
        with:
          repository: nicksya/flux-gitops-kind
          token: ${{ secrets.GH_TOKEN }}

      - name: Install SOPS
        run: |
          curl -L https://github.com/getsops/sops/releases/download/v3.8.1/sops-v3.8.1.linux.amd64 \
            -o /usr/local/bin/sops
          chmod +x /usr/local/bin/sops

      - name: Create secret manifest
        run: |
          cat <<EOF > clusters/kbot/secret.yaml
          apiVersion: v1
          kind: Secret
          metadata:
            name: kbot
          data:
            token: "${{ secrets.TELE_TOKEN }}"
          EOF

      - name: Encrypt with SOPS (age)
        env:
          SOPS_AGE_RECIPIENTS: ${{ secrets.SOPS_AGE_PUBLIC_KEY }}
        run: |
          sops -e clusters/prod/myapp/secret.yaml > \
               clusters/prod/myapp/secret.enc.yaml
          rm clusters/prod/myapp/secret.yaml

      - name: Commit encrypted secret
        run: |
          git add clusters/prod/myapp/secret.enc.yaml
          git commit -m "chore(secrets): rotate myapp API token"
          git push
